name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          git pull

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Start backend server
        run: |
          sudo systemctl restart training-tracker

      - name: Install client dependencies
        run: |
          cd client
          npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Serve client
        run: |
          sudo systemctl restart training-tracker-client
